export const mapper = [
  ['ハーレム', 'Harem'],
  ['シリアス', 'Serious'],
  ['ほのぼの', 'Heartwarming'],
  ['バトル', 'Battle'],
  ['ラブコメ', 'Romcom'],
  ['ハッピーエンド', 'Happy End'],
  ['バッドエンド', 'Bad End'],
  ['嘘コク', 'Fake Confession'],
  ['ギャグ', 'Gag'],
  ['チート', 'Cheat'],
  ['ファンタジー', 'Fantasy'],
  ['スクールラブ', 'School Love'],
  ['ダーク', 'Dark'],
  ['ミステリー', 'Mystery'],
  ['ヒーロー', 'Hero'],
  ['ヒロイン', 'Heroine'],
  ['ダンジョン', 'Dungeon'],
  ['ざまぁ', 'Serves you right'],
  ['ざまあ', 'Serves you right'],
  ['ディストピア', 'Dystopia'],
  ['アイドル', 'Idol'],
  ['成り上がり', 'Nouveau riche'],
  ['ライトノベル', 'Light Novel'],
  ['セフレ', 'Sex friend'],
  ['ホームドラマ', 'Home Drama'],
  ['パラレルワールド', 'Parallel World'],
  ['ヤンデレ', 'Yandere'],
  ['ツンデレ', 'Tsundere'],
  ['ゲーム', 'Game'],
  ['コミカライズ', 'Comicalize'],
  ['アニメ化', 'Anime Adaptation'],
  ['スキル', 'Skill'],
  ['ボーイズラブ', 'BL'],
  ['ガールズラブ', 'GL'],
  ['いじめ', 'Bullying'],
  ['レイプ', 'Rape'],
  ['ロリ', 'Loli'],
  ['コメディ', 'Comedy'],
  ['カクヨムオンリー', 'Kakuyomu Only'],
];

export const tryTranslateKeyword = (keyword: string) => {
  mapper.forEach(([jp, zh]) => (keyword = keyword.replace(jp, zh)));
  return keyword;
};
